---
- name: Ejecutar Insert sql
  hosts: all
  tasks:
    - name: copiar archivo archivo de insercion
      copy:
        src: labansible/files/insert.sql
        dest: prueba/insert.sql
    - name: Ejecutar archivo insert
      mysql_db: name=FARMACIAS state=import target=prueba/insert.sql login_user='root' login_password='Farmacias20$'
