---
- name: Copiar archivos
  hosts: all
  tasks:
    - name: copiar archivo index
      copy:
        src: labansible/files/insert.sql
        dest: prueba/inser.sql
    - name: Ejecutar archivo
      mysql_db: name=FARMACIAS state=import target=prueba/insert.sql login_user='root' login_password='Farmacias20$'
